### PR TITLE
Refined styling

### PR DESCRIPTION
**Pull request by bogdancondorachi**
Removed border radius & increased height to look in alignment with other fields.

### CODE REVIEW

**Comment by fabianmichael** [comment]
@BogdanCondorachi Can you please provide a screenshot?

**Comment by bogdancondorachi** [comment]
Sorry, been really busy and didn't see your message.
Here's how it looks on my project. It was more of a quick fix, didn't have time to dive deeper into it but it works really well so far, even the width aligns perfectly in every scenario.

Web capture_17-1-2022_105756_raumgestalter de
Web capture_17-1-2022_105730_raumgestalter de

**Comment by fabianmichael** [comment]
@BogdanCondorachi Looks great, but it seems like you only committed the build file `index.css`. The styles are defined in the component classes:

- https://github.com/fabianmichael/kirby-multi-toggle-field/blob/main/src/components/MultiToggleInput.vue
- https://github.com/fabianmichael/kirby-multi-toggle-field/blob/main/src/components/MultiToggleInput.vue

Please update these and re-compile the plugin as described in the plugin kit repo: https://github.com/getkirby/pluginkit/tree/4-panel

Thanks! :-)

**Comment by bogdancondorachi** [comment]
I've only edited the css file for those changes. Nothing else needed. I'll have a deeper look and make a better solution when I got some spare time. 

With this lazy solution I don't think the equalize option will work anymore

**Comment by fabianmichael** [comment]
@BogdanCondorachi Thanks, will close this for now. But please aware, that I opted intentionally for rounded corners for giving the element a better visual distinction from regular inputs at the cost of a bit of uniformity.

**Pull request closed without merging**
